<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.kaiqkt.authentication.unit.domain.services.UserServiceTest" tests="4" skipped="0" failures="0" errors="0" timestamp="2025-09-30T21:37:14" hostname="MacBook-Air-de-Kaique.local" time="0.138">
  <properties/>
  <testcase name="given a email and a authentication type should when not exists should throw a exception()" classname="com.kaiqkt.authentication.unit.domain.services.UserServiceTest" time="0.009"/>
  <testcase name="given a user dto when email in use should throw a exception()" classname="com.kaiqkt.authentication.unit.domain.services.UserServiceTest" time="0.001"/>
  <testcase name="given a user dto when is valid should create successfully()" classname="com.kaiqkt.authentication.unit.domain.services.UserServiceTest" time="0.065"/>
  <testcase name="given a email and a authentication type should when exists should return a user()" classname="com.kaiqkt.authentication.unit.domain.services.UserServiceTest" time="0.061"/>
  <system-out><![CDATA[2025-09-30T18:37:14.103-03:00  INFO 15109 --- [kt-authentication-api] [    Test worker] c.k.a.domain.services.UserService        : User 01K6E8XRVPGJMJ6CB0XB5HG731 created successfully
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
